services:
  web:
    build: .
    ports:
    - 80:80
    - 443:443
    depends_on:
    - db
    links:
    - db
  db:
    image: mysql
    volumes:
    - datadb:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=IlEstInterditDeToucher0Ca
volumes:
  datadb: {}
