services:
  web:
    build: .
    ports:
    - 80:80
    - 443:443
    depends_on:
    - db
    links:
    - db
  db:
    image: mysql
    volume:
    - datadb:/var/lib/mysql
    links:
    - web
volumes:
- datadb: {}
